### ISSUE TITLE
Tomita copied copyrighted Google protocol buffers code without proper attribution

### ISSUE THREAD

**Issue by blackgnezdo** [yandex/tomita-parser#10]
This is the code in protocol buffers:
https://code.google.com/p/protobuf/source/browse/trunk/src/google/protobuf/compiler/parser.cc#89

This is a copy of the same code in Tomita:
https://github.com/yandex/tomita-parser/blob/master/src/kernel/gazetteer/common/parserbase.cpp#L10

I believe this violates Google license by not giving credit as required by BSD license which accompanies Protocol Buffers.

**Comment by vbocharov** [comment]
Thank you. I've added copyright notice to parserbase.cpp
