### ISSUE TITLE
Записать произвольный текст в факт

### ISSUE THREAD

**Issue by gv24z** [yandex/tomita-parser#104]
Добрый день. Использую Томиту не совсем по назначению, но всё же.
Есть сайт, где пользователи пишут сообщения. Нужно на каждое из них навешать теги, описывающие его содержание (продажа товаров, доброе утро, реклама...). Теги представляю в Томите как факты.

Проверка происходит следующим образом:
- На вход томиты подаю текст сообщения, в конфиге указываю несколько статей, которые его анализируют.
- Каждая статья описывается грамматикой, которая должна записывать факт с названием тега.

Проблема в том, что в случае соответствия правилам грамматики, в факт нужно записать произвольное значение, которое не упоминается в тексте. 
Например, для текста "Спокойной ночи и самых волшебных снов, друзья!" должен навешиваться тег "Мусор", которого нет в тексте. Соответственно, interp использовать не получается. Подскажите, можно ли в поле факта записать произвольный текст на Томите и если да, то как?

**Comment by vskornyakov** [comment]
Доброго дня.

Вы можете воспользоваться интерпретацией в факт с указанием явного значения, например:
`
SomeText interp (Fact.Field="Мусор");
`

Либо, воспользоваться возможностью задать значение поля факта по умолчанию.

Такие возможности описаны в https://tech.yandex.ru/tomita/doc/dg/concept/interpretation-docpage/

**Comment by gv24z** [comment]
`S -> Adj day interp (TagFact.Tag="Мусор");`
Работает, спасибо! :)
