### ISSUE TITLE
Странная работа парсера

### ISSUE THREAD

**Issue by gv24z** [yandex/tomita-parser#105]
Добрый день.

Случай 1:
Пытаюсь найти с помощью Томиты просьбы о помощи. Пишу такую грамматику:
`#encoding "utf8"
#GRAMMAR_ROOT S

help -> "помоги" Word<gram="V">;
S -> help interp (TagFact.Tag="help"; TagFact.Descr::not_norm);
`

Исходный текст:
`Помогите найти иголку в стоге сена...`

Факт не извлекается. Меняю код:
`help -> "помоги";
S -> help interp (TagFact.Tag="help"; TagFact.Descr::not_norm);`
Факт не извлекается. Чтобы проверить слово в нормальной форме пишу:
`S -> Word interp (TagFact.Tag="help"; TagFact.Descr);`

Результат:
`user@nb001:/mnt/d/tmp/tomita-parser/news$ ~/tomita-parser/build/bin/tomita-parser config.proto
  Compiling news.cxx ...        (5 unique symbols, 3 rules)     OK
[02:02:19 10:24:15] - Start.  (Processing files.)
Помогите найти иголку в стоге сена . . .
        TagFact
        {
                Tag = help
                Descr = помоги
        }
        TagFact
        {
                Tag = help
                Descr = найду
        }
        TagFact
        {
                Tag = help
                Descr = иголка
        }
        TagFact
        {
                Tag = help
                Descr = в
        }
        TagFact
        {
                Tag = help
                Descr = стог
        }
        TagFact
        {
                Tag = help
                Descr = сен
        }
[02:02:19 10:24:15] - End.  (Processing files.)`

Случай 2:
Пытаюсь найти информацию о розыгрышах. Исходный файл:
`Разыгрываем диван за репост`

Вывод в нормальной форме (аналогично предыдущему случаю):
`user@nb001:/mnt/d/tmp/tomita-parser/news$ ~/tomita-parser/build/bin/tomita-parser config.proto
[02:02:19 10:25:40] - Start.  (Processing files.)
Разыгрываем диван за репост
        TagFact
        {
                Tag = help
                Descr = разыгрываем
        }
        TagFact
        {
                Tag = help
                Descr = диван
        }
        TagFact
        {
                Tag = help
                Descr = за
        }
        TagFact
        {
                Tag = help
                Descr = репост
        }
[02:02:19 10:25:40] - End.  (Processing files.)`

Грамматика:
`#encoding "utf8"
#GRAMMAR_ROOT S

help -> "разыгрываем";
S -> help interp (TagFact.Tag="help"; TagFact.Descr::not_norm);`

Факт не извлекается.

Замечено, что если в исходном примере заменить буквы Ы на И, нормальная форма становится другой и грамматика корректно извлекает факт.

Подскажите, в чём причина такого поведения и как можно это обойти?

**Comment by ikor20** [comment]
Используйте неопределенную форму глагола (инфинитив) в лемме. 
В первом случае - "_помочь_", во втором - "_разыгрывать_".
Воспроизвёл у себя, с инфинитивом всё работает.
