### ISSUE TITLE
как отследить начало предложения

### ISSUE THREAD

**Issue by Katerina4545** [yandex/tomita-parser#106]
Конец предложения мы можем зафиксировать пометой EOSent, есть ли подобный способ зафиксировать начало предложения? Чтобы разбор грамматики происходил только лишь в случае, если предложение начинается с описанного правила. Например S-><некоторая помета или грамматика> Noun  Word; такое правило чтобы выделяло предложения, которые начинаются с существительных.

**Comment by ikor20** [comment]
Если вдруг ещё не нашли - помета <fw>
