### ISSUE TITLE
Неопределённость части речи

### ISSUE THREAD

**Issue by ph1ex0n** [yandex/tomita-parser#108]
Вот [тут](https://vinaigrette.ml/ljbot/tomita/lj.0/prettyOutput.html) видно, что в последнем предложении

> Хоть   бы   с   концертом   в   Сухуми   приехала   ,   что   ли   .   EOS

слово "ли" даёт три части речи.

Вопрос - какую часть речи выбирать для "ли" при работе скрипта по автоматическому определению части речи конкретного слова?

**Comment by grandsbor** [comment]
Вы не могли бы подробнее описать свою задачу? Для определения частей речи парсер не особенно подходит.

**Comment by ph1ex0n** [comment]
какую часть речи выбирать для "ли" после майстема?

**Comment by grandsbor** [comment]
Понятнее не стало :) Вы хотите выбрать часть речи, чтобы что делать с этой информацией дальше?

**Comment by ph1ex0n** [comment]
в принципе, не имеет значения что делать дальше, важно - как интерпретировать эту неоднозначность

**Comment by grandsbor** [comment]
Если неважно, что делать дальше, то можно интерпретировать как угодно, нет?

Но, например, по принципам разметки в Открытом корпусе это [частица](http://opencorpora.org/manual.php?pool_type=53#.D0.9B.D0.B8_.28.D0.BB.D1.8C.29).

**Comment by ph1ex0n** [comment]
нет, интерпретация должна быть однозначной, как в открытом корпусе

**Comment by grandsbor** [comment]
> Вопрос - какую часть речи выбирать для "ли" при работе скрипта по автоматическому определению части речи конкретного слова?

> интерпретация должна быть однозначной

Если вы пишете такой скрипт, то можете внести условие вида: _ли_ в выражении "что ли" - частица.

**Comment by ph1ex0n** [comment]
крутое решение
