### ISSUE TITLE
Неопределенность при определении существительного

### ISSUE THREAD

**Issue by kovalexal** [yandex/tomita-parser#112]
Здравствуйте!
Столкнулся с следующей проблемой. При определении части речи парсер не распознает некоторые существительные, в основном составные с несколькими корнями. При этом, часть из них он успешно распознает.
Грамматика очень простая:
S -> Noun interp (Fact.Obj);

Например, слово АВТОКРАН для него - существительное, а АВТОВЫШКА - нет (при этом слова КРАН и ВЫШКА - существительные). Другие примеры слов, для которых часть речи не определена (UnknownPOS):
- КОФЕМАШИНА
- МАШИНОМЕСТО
- МИНИПОГРУЗЧИК
- ВИДЕООБОРУДОВАНИЕ

Подскажите, почему так происходит, и есть ли способ как-то повлиять на это?

**Comment by victorbocharov** [comment]
Морфологический разбор делает mystem, повлиять на него нельзя, т.к. он поставляется без исходного кода.

Но можно управлять использованием гипотез для несловарных слов при помощи параметра конфига ```BastardMode```. По умолчанию он выставлен в значение ```no```, т.е. не использовать предиктивную морфологию. Значение ```outOfDict``` помогает с перечисленными словами.

Подробнее: https://github.com/yandex/tomita-parser/commit/cc0429393db8fc20600cdfb92dd4de82eb036244#diff-4406c91c65ad894f8847ccf973d90f75562788498c382f32d73bb26dcc5884b4
