### ISSUE TITLE
На найден файл - articles_base.pb.h

### ISSUE THREAD

**Issue by MaIronCool** [yandex/tomita-parser#115]
Большая часть проекта собралась. Но при сборке не находит - articles_base.pb.h
В чем проблема?

_c:\tomita-parser\src\factextract\parser\afdocparser\common\langdata.h(8): fatal error C1083: Не удается открыть файл включение: FactExtract/Parser/afdocparser/builtins/articles_base.pb.h: No such file or directory_

Собираю под Win7, VS2013 и CMake (cmake-gui)

**Comment by grandsbor** [comment]
cc @victorbocharov

**Comment by MaIronCool** [comment]
Не на 100% уверен, что правильно сделал, но собрал под Win7.
Кому интересно описываю сборку под Windows. Отключаем антивирусы.

Ставим VS2013 (только под дней собралось), ActivePerl, и CMake.
В CMake в графическом режиме выбираем каталог исходных файлов C:\tomita-parser-master\src и каталог выходных файлов C:\tomita-parser-master\build

Нажимаем **Configure**.
Потом **Generate** 

Появляется невероятных размеров решение для VS с сотней проектов.
Запускаем сборку. Вываливаются несколько ошибок, не глобальных, вроде несовпадения типов.
Не пугаемся - правим, 

Последней была ошибка в файле normalization.cpp
```
static const Wtroka delims = CharToWide("_ ");
StringTokenizer<Wtroka> words(w.GetText(), delims);

```
Заменил на:
`StringTokenizer<Wtroka> words(w.GetText(), TChar("_ "));`

После этого все собралось.
