### ISSUE TITLE
Указать папку с исходными данными 

### ISSUE THREAD

**Issue by roosyak** [yandex/tomita-parser#116]
Можно ли в конфиге указать папку, из которой томита возьмёт несколько файлов с текстами? 
В таком случае, куда будут записаны результаты?

**Comment by ikor20** [comment]
Можно, вместо 
`File = "YOUR_FILE_NAME"`
укажите
`Dir = "YOUR_DIRECTORY_NAME"`
Результаты будут записываться в один файл поддерживаемого формата, указанный в поле Output.

**Comment by roosyak** [comment]
исправил
```
encoding "utf8";
TTextMinerConfig {
  Dictionary = "abr/mydic.gzt";
  Input = {
    //File = "abr/test.txt"; // путь к входному файлу
	Dir = "abr/in"
  }
  Articles = [
    { Name = "АБР" }
  ]
  Facts = [
    { Name = "ABR" }
  ]
  Output = {
    File = "abr/facts.txt";
    Format = text;
  }
}
```
в папке «abr/in» лежит два файла:

- test.txt
- copy.txt

в файле результата «facts.txt» имеется содержание из файла «test.txt», второго файла (copy.txt) нет. 
В чём может быть проблема?

**Comment by roosyak** [comment]
Если указать 
- File = "abr/facts.xml";
- Format = xml;

то нормально создаётся два блока:
 ```
<document url="\copy.txt" di="-1" bi="-1" date=""> 
<document url="\test.txt" di="-1" bi="-1" date="">
```
