### ISSUE TITLE
Исключение повторений

### ISSUE THREAD

**Issue by 515** [yandex/tomita-parser#125]
Подскажите пожалуйста - нигде не могу найти, как исключить дубли. Скажем я написал условие, которое повторяется несколько раз и в результатах выводятся дубли.

City
--
г. Оренбург
г. Оренбурга
г. Оренбурга
г. Оренбурга

Написать более точное указание факта не предоставляеться возможным - так, как источники меняются.

**Comment by victorbocharov** [comment]
Пока не понимаю, о чём идёт речь. Приведите, пожалуйста, пример.

**Comment by 515** [comment]
В документе попадается упоминание города несколько раз и нет четкого шаблона где название города может находится, поэтому ищу его по признаку г. или город. Соответственно в факты вытаскивается его название (города) столько раз, сколько парсер нашел упоминаний о нем. 
1. Вопрос можно ли сделать так, чтобы парсер искал к примеру только первое соответствие?
2. Вопрос можно ли сделать так, чтобы парсер не вытаскивал дубли в разных склонениях?

**Comment by victorbocharov** [comment]
> Вопрос можно ли сделать так, чтобы парсер искал к примеру только первое соответствие?

Нет. Он работает по отдельным предложениям. Исключение - встроенный алгоритм ФИО, где он кластеризует ФИО внутри документа.

> Вопрос можно ли сделать так, чтобы парсер не вытаскивал дубли в разных склонениях?

Если при интерпретации не указано ::not_norm , то он нормализует к "словарной форме", если это известное слово или если он правильно угадал граммемы неизвестного. Для "Оренбурга" всё правильно: оренбург S, geo, gen, sg, m, inan . Нормализует тоже правильно:

```
Root -> Word interp(Fact1.Name);
```

даёт
```
Оренбурга 
	Fact1
	{
		Name = оренбург
	}
```

**Comment by 515** [comment]
Нормализацией я пользоваться научился - я наверное просто неверно задал вопрос - мне не нужны дубли просто - не важно в каком они склонении. Нужен только 1 вариант!

**Comment by victorbocharov** [comment]
Это можно сделать только постобработкой результатов. Томита не умеет фильтровать. Сгенерировала и забыла.

**Comment by 515** [comment]
Спасибо большое, буду знать!

**Comment by victorbocharov** [comment]
Закройте, пожалуйста, те issue, по которым у вас больше нет вопросов. Так их проще отслеживать.
