### ISSUE TITLE
Поиск по статическому шаблону

### ISSUE THREAD

**Issue by 515** [yandex/tomita-parser#127]
Есть исходник:
**рассмотрев   в   открытой   форме   обращения**
Пробовал так:
```
#encoding "utf-8"
form -> 'открытая | 'закрытая';
searchtype -> form AnyWord;
type1 -> 'в' searchtype interp (Form.Type);
```
`
AnyWord<wff=/в(( открытой| закрытой) форме   обращения)/>; `- регулярное выражение так же не работает

Не пойму как искать все слова в словарь засовывать?

**Comment by victorbocharov** [comment]
Регулярки работают только на отдельных словах.

Слова в кавычках в правой части должны быть в словарной форме. У прилагательных - это мужской род, единственное число, именительный падеж. У вас - женский род. Если заменить на мужской - заработает вот так:

```
рассмотрев в открытой форме обращения 
	Form
	{
		Type = открытая форме
	}
```

По умолчанию парсер считает, что первое слово в правой части правила - главное. И только его и нужно нормализовывать. Чтобы сделать главным не первое - поставьте помету `rt`, чтобы нормализовывал нужным образом - поставьте согласование (в данном случае - по роду, числу и падежу - `gnc-agr`). Теперь вот так:

```
рассмотрев в открытой форме обращения 
	Form
	{
		Type = открытая форма
	}
```

Для полноты картины (не меняет результата, но может пригодиться позже): `AnyWord ` заменяем на существительное `Word<gram="S">` + предложный падеж после `в`:

```
#encoding "utf-8"

form -> 'открытый' | 'закрытый';
searchtype -> form<gnc-agr[1]> Word<rt, gram="S", gnc-agr[1]>;
type1 -> 'в' searchtype<gram="пр"> interp (Form.Type);
```
