### ISSUE TITLE
Три вопроса - поиск по шаблону

### ISSUE THREAD

**Issue by 515** [yandex/tomita-parser#128]
Исходиник: **разбирательство № 1-85/2020**
1. Почему не работает?
`casenumber -> <wff=/[0-9]?[0-9]?[0-9]-[0-9]?[0-9]?[0-9]"/"[0-9][0-9]?[0-9]?[0-9]/>;`

2. Почему не работает?
`casenumber -> "№" AnyWord;`

3. Почему не работает?
`casenumber -> "разбирательство" "№" <wff=/[0-9]?[0-9]?[0-9]-[0-9]?[0-9]?[0-9]"/"[0-9][0-9]?[0-9]?[0-9]/>;`

**Comment by e-vasin** [comment]
На сколько я помню слеш делит номер на три слова: 1-85 / 2020

вт, 27 окт. 2020 г., 18:19 515 <notifications@github.com>:

**Comment by 515** [comment]
Спасибо большое! Так и оказалось
