### ISSUE TITLE
Пропуск неопределенного количества слов

### ISSUE THREAD

**Issue by 515** [yandex/tomita-parser#131]
Есть текст
_Вывод:
В результате разбора обстоятельств, заместитель директора Сучкова Н.В установила ссылаясь на правила поведения предусмотренных в ч.3 п.4 правил поведения и этических норм, лишить Вязкова В.А премии, с последующим освобождением от занимаемой должности._
Как в даном случае мне выбрать неизвестное количество слов от одного ориентира до другого?
Например регулярным выражением я могу сделать так, чтобы выбрать вывод 
`(Вывод:)?.*[^. ]`

Допустим я хочу искать фамилии после слова **Вывод:**
Есть ли возможность просто пропустить слова после **Вывод:** до слова **лишить** к примеру?

**Comment by ikor20** [comment]
"вывод" AnyWord* "лишить"

**Comment by 515** [comment]
Спасибо. А не подскажите еще - Допустим я нашел нужный диапазон - как мне в нем теперь искать?

**Comment by victorbocharov** [comment]
Вот так?
```
S -> "вывод" AnyWord* "лишить" FioRule;
```

**Comment by 515** [comment]
А может быть есть возможность сначала обозначить диапазон для поиска и только потом искать?

**Comment by victorbocharov** [comment]
Если есть какие-то очевидные маркеры, по которым можно выделить текст, который вы собираетесь анализировать, то можно сделать это до томиты. Регуляркой или другим запуском томиты с другой грамматикой. Стоит ли это делать - вопрос качества маркеров (к каким потерям полноты / точности приводит их использование) и скорости.

Есть возможность ограничить запуск конкретной грамматики (файла .cxx) подмножеством предложений, в которых есть какие-то слова или цепочки слов. Это называется фильтром: 

https://github.com/yandex/tomita-parser/blob/master/docs/ru/dg/syntax-grammars.md#filter

Фильтры предназначены для увеличения скорости работы.

**Comment by 515** [comment]
Понял
