### ISSUE TITLE
LBracket - RBracket - не работают. Что я делаю не так?

### ISSUE THREAD

**Issue by 515** [yandex/tomita-parser#133]
Из документации:
LBracket | Открывающая скобка.
RBracket | Закрывающая скобка.

Исходный текст:
_Отгружено коробок: мороженое 12 шт. (2 открытых),_

`LBracket Word<wff=/[0-9]/> open RBracket `- не работает. Что я не так делаю?

**Comment by victorbocharov** [comment]
как выглядит правило, задающее `open`?

**Comment by 515** [comment]
> как выглядит правило, задающее `open`?
Это слово в словаре
open -> Word<kwtype=open>;

Если убрать скобки, то работает

**Comment by victorbocharov** [comment]
Какие слова перечисленны в статье газеттира `open`?

**Comment by 515** [comment]
Открытый, закрытый

Не могу точно понять с чем это связано но все заработало.

**Comment by 515** [comment]
Спасибо за неравнодушие!
