### ISSUE TITLE
Кэширование

### ISSUE THREAD

**Issue by 515** [yandex/tomita-parser#134]
Заметил такую особенность - я что-либо закомментировал, а томита-парсер продолжает какое-то время выполнять то, что я закомментировал. Я так понимаю это что-то типа кэширования - как это отключить?

**Comment by victorbocharov** [comment]
Кеширования нет. Наблюдаемый эффект, вероятно, связан с чем-то другим.

Парсер использует скомпилированные грамматики (.bin). Если исходник (.cxx) новее, чем соответствующий ему бинарный файл, то исходник будет перекомпилирован перед загрузкой бинарного файла.

Во время обработки потока документов перекомпиляции не происходит. Т.е. если вы запустили парсинг, а после изменили грамматику, то парсинг и далее будет работать по старой грамматике до завершения процесса tomita-parser. При следующем старте произойдёт перекомпиляция.

Т.е. чтобы парсер начал работать по обновлённой грамматике его надо запустить заново.

О том, что происходит компиляция исходников грамматики он пишет в консоль:

```
  Compiling "dic.gzt" ... OK 
  Compiling bornin.cxx ... 	(15 unique symbols, 12 rules)	OK
```

Если вы видите признаки того, то реальное поведение парсера отличается от ожидаемого (см. выше), то попробуйте что-то из перечисленного ниже:

- опция конфига ForceRecompile заставляет пересобирать грамматики при каждом запуске вне зависимости от времени изменения исходников
- удаление бинарный файлов (*.bin) должно давать аналогичный эффект
- опция конфига BinaryDir позволяет указать альтернатвиное место для хранения скомпилированных грамматик
- проверьте, обновляется ли метка времени исходников при сохранении, нет ли каких-то экзотических настроек при монтировании файловой системы, которые могли бы привести к тому, что метка времени при сохранении не всегда обновляется.

**Comment by victorbocharov** [comment]
Возможно, что это та же проблема, что в #58
