### ISSUE TITLE
Передача параметров при запуске

### ISSUE THREAD

**Issue by 515** [yandex/tomita-parser#136]
Допустим в config.proto мне нужно передать сначала
```
Input = {
    File = "part1.txt";
  }
```
а затем скажем
```
Input = {
    File = "part2.txt";
  }
```
Как это сделать?
P.S
Как вариант конечно можно создать несколько конфигов - но может есть какой-то более правильный вариант?

**Comment by victorbocharov** [comment]
Параметры конфига:
- Dir (вместо File) позволяет указать папку
- Type (работает с одним файлом) позволяет указать тип входного файла. Например, можно сделать Type=tar, чтобы читать tar архив

Вот тут все параметры конфига:
https://github.com/yandex/tomita-parser/blob/master/src/FactExtract/Parser/common/textminerconfig.proto
