### ISSUE TITLE
Кодировка Lemma.{StemGram,FlexGram}

### ISSUE THREAD

**Issue by dustalov** [yandex/tomita-parser#14]
Результаты обработки слова при помощи mystem в `FactExtract/Parser/lemmerlib/extlemmer.cpp` (метод `CopyFromMystem`) записываются функцией `SetLemma` в экземпляр класса `TSimpleLemma`, её реализация приведена в `FactExtract/Parser/lemmerlib/lemma.cpp`.

Насколько я понял, поля `LemmaText` и `FormNormalized` кодируются в виде двухбайтовых символов с использованием Unicode.

В какой кодировке представлены поля `StemGram` и `FlexGram`, являющиеся `char *`? Где ставится соответствие между "Noun" в грамматике (`cxx`) и частью речи из результатов морфологического анализа?

**Comment by alzobnin** [comment]
LemmaText и FormNormalized - это двухбайтный Unicode, да.

StemGram и FlexGram - это NULL-terminated строки, каждый байт которой - это enum TGrammar из src/library/lemmer/dictlib/yx_gram_enum.h

**Comment by dustalov** [comment]
Сработало. Большое спасибо!
