### ISSUE TITLE
Сравнения распознанных чисел

### ISSUE THREAD

**Issue by KotIva** [yandex/tomita-parser#143]
Здравствуйте, подскажите пожалуйста, умет ли Томита сравнивать 2 распознанных факта (оба факта - числа) ?

**Comment by victorbocharov** [comment]
Не уверен, что понимаю. Что должно случиться в результате сравнения?

**Comment by KotIva** [comment]
Должен быть извлечен только 1 факт, например наибольшее число из 2 найденных в тексте.

**Comment by victorbocharov** [comment]
Нет, так нельзя.

**Comment by KotIva** [comment]
Понял, спасибо.
