### ISSUE TITLE
Спец символы в газеттире

### ISSUE THREAD

**Issue by informixter** [yandex/tomita-parser#145]
Здравствуйте. Когда описываю в ключе газеттира знак **&**, то он его не находит. Подскажите как экранировать или прописать данный символ, что он находил ключевое слово?
```
company "SP500"
{
    key = "S&P 500"
    lemma = "SP500"
}
```

**Comment by victorbocharov** [comment]
Статья для газеттира правильная. Экранировать не нужно. Проблема в том, что сегментатор делит "S&P 500" на четытре токена (S & P 500). 

Можно сделать вот так:

```
company "SP500"
{
    key = "S & P 500"
    lemma = "SP500"
}
```

Чтобы посмотреть, как парсер сегментирует текст, включите в конфиге PrettyOutput (осторожно, на большом тексте он израсходует всю память и упадёт по OOM). Он сгенерирует html файл с разбивкой по токенам, предложениям и фактам.

**Comment by informixter** [comment]
Спасибо большое, что ответили.
