### ISSUE TITLE
Нормализация при использовании словаря type=FILE

### ISSUE THREAD

**Issue by e-vasin** [yandex/tomita-parser#146]
Доброго времени суток.
Есть словарь городов:
```
TAuxDicArticle "city" {
    key = {"cities.txt" type=FILE}
}
```
содержимое cities.txt:
```
Абакан
Екатеринбург
Нижний Новгород
Тюмень
```
И есть грамматика:
```
#encoding "utf8"
Return -> AnyWord<kwset="city"> interp(TestFact.B::norm="nom");
```
При парсинге фразы "В Нижнем Новгороде началось собрание..." в поле факта TestFact.B пишется "НИЖНИЙ НОВГОРОДЕ".
Есть ли возможность указать, что все слова записи в словаре должны быть согласованы, например по nc-agr, или нормализацию для мультивордов можно проводить только через отдельные словари, как в [документации](https://github.com/yandex/tomita-parser/blob/master/docs/ru/dg/interpretation.md#%D0%BD%D0%BE%D1%80%D0%BC%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-)?
Указание согласования в описании словаря `key = {"cities.txt" type=FILE agr=nc_agr}` не даёт эффекта.

**Comment by victorbocharov** [comment]
Для многословных элементов газетира нужно указывать согласование и главное слово. Вот [тут](https://github.com/yandex/tomita-parser/blob/master/docs/ru/dg/gazetteer-syntax.md) об этом написано. По умолчанию первое слово - главное. Если не указан тип согласования, то парсер не знает как нормализовывать последующие слова.

Многословные элементы газетира имеет смысл записать отдельными статьями, указав тот же тип статьи. [Вот пример](https://github.com/yandex/tomita-parser/blob/master/examples/bornin/dic.gzt), где у нескольких статей один тип.

**Comment by e-vasin** [comment]
Понял, спасибо
