### ISSUE TITLE
Верхний регистр букв в выдаче Tomita

### ISSUE THREAD

**Issue by vorslov** [yandex/tomita-parser#19]
Добрый день!
Буду благодарен если направите в нужном направлении...
Атрибуты val узлов результирующего XML в результате обработки преобразуются к верхнему регистру.
Наверно, я что то делаю не так.
Заранее спасибо за ответ.
На вход Tomita (работает на FreeBSD) подается текст:

Контакты

Центральный офис Группы компаний «Батыр»: 450027, г. Уфа, Индустриальное шоссе, 47 Установка и обслуживание информационно-правовой системы Дата проведения 16 мартa 2015 г. Всю информацию по тендеру согласно инструкции для партнеров необходимо направить до 15 марта 2015 г., на адрес электронной почты tender@bashpost.ru  По всем вопросам обращаться по телефону: (347)246-79-79.
Начало активности (дата): 
Окончание активности (дата): 
Установка и обслуживание информационно-правовой системы
Техзадание на установку и обслуживание информационно-правовой системы для ГК «Батыр»
 
Информационно-правовая система должна быть расчитана на 40-50 рабочих мест (В настоящее время используются 43 рабочих места).
Система должна обеспечивать удобный поиск, возможность перехода из документов на связанные по смыслу документы.
Должны быть представлены актуальные данные на текущую дату по правовой информации для работы юриста, бухгалтера, кадровика.
 
Наличие в системе нижеперечисленных разделов или аналогичных им:
Судебная практика для бухгалтера, Путеводитель по налогам, Путеводитель по кадровым вопросам, Путеводитель по сделкам для бухгалтера, Бухгалтерская пресса и книги
Бланки и правила оформления деловых бумаг
Корреспонденции счетов
Комментарии законодательства (Постатейные комментарии и книги, Путеводитель по договорной работе, Путеводитель по судебной практике (ГК РФ), Путеводитель по корпоративным процедурам, Путеводитель по корпоративным спорам, Путеводитель по трудовым спорам, Путеводитель по госуслугам для юридических лиц, Путеводитель по контрактной системе в сфере госзакупок, Путеводитель по спорам в сфере госзаказа, Юридическая пресса
ФАС всех округов
Законодательство Башкортостана
Судебная практика судов общей юрисдикции
Судебная практика арбитражных судов
Решения высших судов (включая акты Суда по интелектуальным правам)
Флеш-версия информационно-правовой системы.

-------------------------------------------------

на выходе получаю:

&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;fdo_objects&gt;
&lt;document date="2015-03-24" bi="-1" di="0" url=""&gt;
&lt;facts&gt;
&lt;Zakazchik lw="4" fw="0" sn="1" len="39" pos="11" FieldsInfo="n0;n1;" LeadID="0" FactID="0"&gt;
&lt;Stroka_Zakazchik val="ЦЕНТРАЛЬНЫЙ ОФИС"/&gt;
&lt;Zakazchik_name val="ГРУППА КОМПАНИЙ БАТЫР"/&gt;
&lt;/Zakazchik&gt;
&lt;Predmet lw="21" fw="5" sn="1" len="98" pos="51" FieldsInfo="n2;n3;" LeadID="0" FactID="1"&gt;
&lt;Stroka_Predmet val=": 450027, Г. УФА, ИНДУСТРИАЛЬНОЕ ШОССЕ, 47"/&gt;
&lt;Predmet_tendera val="УСТАНОВКА И ОБСЛУЖИВАНИЕ ИНФОРМАЦИОННО-ПРАВОВОЙ СИСТЕМЫ"/&gt;
&lt;/Predmet&gt;
&lt;Data_Priema_Zayavok lw="39" fw="27" sn="1" len="93" pos="187" FieldsInfo="n4;n5;" LeadID="0" FactID="2"&gt;
&lt;Stroka_Data_Priema val="ИНФОРМАЦИЯ ПО ТЕНДЕРУ СОГЛАСНО ИНСТРУКЦИИ ДЛЯ ПАРТНЕРОВ НЕОБХОДИМО НАПРАВИТЬ ДО"/&gt;
&lt;Data_priema val="15 МАРТА 2015"/&gt;
&lt;/Data_Priema_Zayavok&gt;
&lt;/facts&gt;
&lt;Leads&gt;
&lt;Lead id="0" text="&lt;l&gt;&lt;h t="ya" di="0" u=""&gt;&lt;d&gt;2015-03-24 23:22&lt;/d&gt;&lt;s&gt;file&lt;/s&gt;&lt;/h&gt;&lt;b&gt;&lt;s&gt;&lt;S n0="" lemma="центральный офис"&gt;Центральный офис&lt;/S&gt; &lt;Z n1="" lemma="Группа компаний Батыр"&gt;Группы компаний "Батыр"&lt;/Z&gt;&lt;S n2="" lemma=": 450027, г. Уфа, Индустриальное шоссе, 47"&gt;: 450027, г. Уфа, Индустриальное шоссе, 47&lt;/S&gt; &lt;P n3="" lemma="Установка и обслуживание информационно-правовой системы"&gt;Установка и обслуживание информационно-правовой системы&lt;/P&gt; Дата проведения 16 марта 2015 г. Всю &lt;S n4="" lemma="информация по тендеру согласно инструкции для партнеров необходимо направить до"&gt;информацию по тендеру согласно инструкции для партнеров необходимо направить до&lt;/S&gt; &lt;D n5="" lemma="15 марта 2015"&gt;15 марта 2015&lt;/D&gt; г., на адрес электронной почты tender@bashpost.ru По всем вопросам обращаться по телефону: ( 347 ) 246-79-79.&lt;/s&gt;&lt;/b&gt;&lt;/l&gt;"/&gt;
&lt;/Leads&gt;
&lt;/document&gt;
&lt;/fdo_objects&gt;

**Comment by vorslov** [comment]
Дополнение:
Если же в качестве выходного формата поставить не XML а TEXT, то с верхнем регистром нет проблем:

Контакты
Центральный офис Группы компаний "Батыр" : 450027 , г. Уфа , Индустриальное шоссе , 47 Установка и обслуживание информационно-правовой системы Дата проведения 16 марта 2015 г. Всю информацию по тендеру согласно инструкции для партнеров необходимо направить до 15 марта 2015 г. , на адрес электронной почты tender@bashpost.ru По всем вопросам обращаться по телефону : ( 347 ) 246-79-79 .
        Zakazchik
        {
                Stroka_Zakazchik = центральный офис
                Zakazchik_name = Группа компаний "Батыр"
        }
        Predmet
        {
                Stroka_Predmet = : 450027, г. Уфа, Индустриальное шоссе, 47
                Predmet_tendera = Установка и обслуживание информационно-правовой системы
        }
        Data_Priema_Zayavok
        {
                Stroka_Data_Priema = информация по тендеру согласно инструкции для партнеров необходимо направить до
                Data_priema = 15 марта 2015
        }
Начало активности ( дата ) : Окончание активности ( дата ) : Установка и обслуживание информационно-правовой системы Техзадание на установку и обслуживание информационно-правовой системы для ГК "Батыр"
Информационно-правовая система должна быть расчитана на 40-50 рабочих мест ( В настоящее время используются 43 рабочих места ) .
Система должна обеспечивать удобный поиск , возможность перехода из документов на связанные по смыслу документы .
Должны быть представлены актуальные данные на текущую дату по правовой информации для работы юриста , бухгалтера , кадровика .
Наличие в системе нижеперечисленных разделов или аналогичных им : Судебная практика для бухгалтера , Путеводитель по налогам , Путеводитель по кадровым вопросам , Путеводитель по сделкам для бухгалтера , Бухгалтерская пресса и книги Бланки и правила оформления деловых бумаг Корреспонденции счетов Комментарии законодательства ( Постатейные комментарии и книги , Путеводитель по договорной работе , Путеводитель по судебной практике ( ГК РФ ) , Путеводитель по корпоративным процедурам , Путеводитель по корпоративным спорам , Путеводитель по трудовым спорам , Путеводитель по госуслугам для юридических лиц , Путеводитель по контрактной системе в сфере госзакупок , Путеводитель по спорам в сфере госзаказа , Юридическая пресса ФАС всех округов Законодательство Башкортостана Судебная практика судов общей юрисдикции Судебная практика арбитражных судов Решения высших судов ( включая акты Суда по интелектуальным правам ) Флеш-версия информационно-правовой системы .

**Comment by vorslov** [comment]
Получил ответ от Яндекса:

Нет. Вы всё делаете правильно.

Это действительно так. 

Если Вы хотите получить строку в том виде, в котором она была написана, то нужно либо парсить лиды (<Leads>), либо использовать другие форматы вывода (например, txt).

В opensource версии (https://github.com/yandex/tomita-parser) есть ещё и вывод в json. Его, возможно, парсить легче. Примеры там же есть.

**Comment by vbocharov** [comment]
Закрываем issue? ;)
