### ISSUE TITLE
Лимит фактов: 25

### ISSUE THREAD

**Issue by hemsonolev** [yandex/tomita-parser#20]
По умолчанию стоит лимит фактов: 25, как можно его увеличить? где в коде прописать значение и собрать программу?

**Comment by vbocharov** [comment]
Не изменять в коде. Нужно в конфиге выставить параметр MaxFactsCountPerSentence в нужное значение. Все параметры, которые можно выставлять в конфиге, описаны тут:

https://github.com/yandex/tomita-parser/blob/master/src/FactExtract/Parser/common/textminerconfig.proto

**Comment by hemsonolev** [comment]
Это прописывать при компиляции или просто в конфиге обрабатывая текст?
Второй вариант не сработал:

```
encoding "utf8";

TTextMinerConfig {
    optional uint32 MaxFactsCountPerSentence = 100;
    
    Dictionary = "dic.gzt";

    Input = {
        File = "words.txt";
    }

    Articles = [
        {Name = "normal_word"}
    ]
  
    Output = {
        File = "out.xml";
        Format = xml;
    }

    Facts = [
        {Name = "normal_word"}
    ]
    
}
```
```
config.proto: Incompatible value assigned to field "TTextMinerConfig.Dictionary".
[27:04:15 11:30:23] - Bad parameters.
FactExtract/Parser/common/commonparm.cpp:340: Cannot read the config from "config.proto".  (Processing files.)
```

**Comment by ivan2kh** [comment]
В официальном релизе на сайте Яндекс этого нет. Думаю, нужно собрать свежую версию из мастер бранча.

**Comment by hemsonolev** [comment]
Скомпилил, не есть конфиг с этой переменной... разные варианты написания пробовал.
можно живой конфиг с лимитом 100 или 1000 фактов?

**Comment by ivan2kh** [comment]
Проверил под linux, работает:

TTextMinerConfig {
  MaxFactsCountPerSentence = 100;
...

**Comment by hemsonolev** [comment]
Да, заработало, спасибо!
