### ISSUE TITLE
Is it possible to port Tomita to parse Italian language?

### ISSUE THREAD

**Issue by lonlylocly** [yandex/tomita-parser#21]
Добрый день.

Скажите пожалуйста, возможно ли адаптировать Томиту для другого языка?
В первую очередь интересен итальянский.

Спасибо.

С уважением,
Николай Васильев.
vasiliev@spaziodati.eu

**Comment by grandsbor** [comment]
Здравствуйте.

Как таковая адаптация почти не требуется, но нужна морфология соответствующего языка. Либо в виде готового модуля, реализующего нужный интерфейс, либо в виде словаря (например, в формате АОТ)

**Comment by lonlylocly** [comment]
Спасибо. 
Насколько я понимаю, Томите нужно дать некое подобие POS-tagger, тогда она будет способна применить свои правила к цепочке лемм (с грамматическими свойствами). Правильно?

**Comment by grandsbor** [comment]
Да, вроде того
