### ISSUE TITLE
CMake зависает при конфигурации

### ISSUE THREAD

**Issue by dustalov** [yandex/tomita-parser#22]
При выполнении команды `cmake ../src/ -DMAKE_ONLY=FactExtract/Parser/tomita-parser -DCMAKE_BUILD_TYPE=Release` процесс зависает и потребляет 100 % процессорного времени. Добавление ключа `--trace` показывает бесконечно печатаемые строки следующего вида.

```
Some weird path(9999):  EOF_HOOK(CMAKE_BACKWARDS_COMPATIBILITY UNKNOWN_READ_ACCESS    )
/tomita/src/cmake/include/buildrules.cmake(1011):  IF(${variable} STREQUAL CMAKE_BACKWARDS_COMPATIBILITY AND ( ${access} STREQUAL UNKNOWN_READ_ACCESS OR ${access} STREQUAL READ_ACCESS ) )
Some weird path(9999):  EOF_HOOK(CMAKE_BACKWARDS_COMPATIBILITY UNKNOWN_READ_ACCESS    )
/tomita/src/cmake/include/buildrules.cmake(1011):  IF(${variable} STREQUAL CMAKE_BACKWARDS_COMPATIBILITY AND ( ${access} STREQUAL UNKNOWN_READ_ACCESS OR ${access} STREQUAL READ_ACCESS ) )
/tomita/src/cmake/include/buildrules.cmake(1013):  IF(UNIT_MACRO_PRESENT AND NOT END_MACRO_PRESENT )
```

Проблема стабильно воспроизводится на Fedora 22 (gcc 5.1.1, cmake 3.3.1, lua 5.3), Debian Jessie (Docker, gcc 4.9.2, cmake 3.0.2, lua 5.2) и Debian Jessie (Docker, gcc 4.8.4, cmake 3.0.2, lua 5.2). Команда выполняется в чистой и корректно расположенной директории `build`.

**Comment by slavas490** [comment]
на ubuntu 15.04 так же

**Comment by vbocharov** [comment]
Нужен cmake 2.8. С cmake 3.* не работает.

**Comment by dustalov** [comment]
Спасибо, помогло. Поскольку установка CMake 2.8 в Debian показалась нетривиальной, я использовал образ Debian Wheezy вместо Jessie. Docker-образ собранной и работающей «Томиты» доступен в репозитории [nlpub/tomita-docker](https://github.com/nlpub/tomita-docker) и в ближайшем времени будет загружен на [Docker Hub](https://hub.docker.com/r/nlpub/tomita/).

**Comment by grandsbor** [comment]
Похоже, я с таким сталкивался на маке
