### ISSUE TITLE
Репа на английском а поддержки английской грамматики нету?

### ISSUE THREAD

**Issue by dyatlov** [yandex/tomita-parser#26]
Ткните носом куда копать

**Comment by irinfox** [comment]
Репозиторий на английском, т.к. подобный инструмент по работе с русским языком может быть интересен не только русскоязычному сообществу.
Вы можете внести свой вклад, собрать английскую морфологию и подключить её к парсеру. Именно для того, чтоб такое было возможно, инструмент и выложен на гитхаб.

**Comment by cblp** [comment]
@irinfox, инструменты для работы с английском морфологией, такие же хорошие, как и для русской, уже есть есть у Яндекса. Только русский язык они выложили, а английский — нет.

**Comment by irinfox** [comment]
AFAIK Томита внутри Яндекса не использовалась для английского. Откуда у вас данные про то, что у Яндекса есть такие же хорошие инструменты для английской морфологии, как и для русской, я не знаю. Но mystem, морфология которого используется под капотом Томиты, работает ТОЛЬКО с русским языком: https://tech.yandex.ru/mystem/

Томита никогда не позиционировалась как универсальный для всех языков инструмент. Для английского есть свои подобные инструменты: https://gate.ac.uk/
Тут есть перечисление других и подобных инструментов с поддержкой языков: https://nlpub.ru/Обработка_текста
