### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by pandreym** [yandex/tomita-parser#30]
Cmake:
Configuring done
-- Generating done
-- Build files have been written to: ***/tomita-parser/build
make 
[  0%] Building CXX object library/malloc/system/CMakeFiles/library-malloc-system.dir/malloc-info.cpp.o
c++: error: science: No such file or directory
c++: error: challenge/tomita-parser/src/library/malloc/system: No such file or directory
make[2]: *** [library/malloc/system/CMakeFiles/library-malloc-system.dir/malloc-info.cpp.o] Error 1
make[1]: *** [library/malloc/system/CMakeFiles/library-malloc-system.dir/all] Error 2

**Comment by the31k** [comment]
Hi @pandreym. Try the branch in PR to see if it will fix the issue for you please.

**Comment by pandreym** [comment]
Yeap, this fix my problem
But another there:
src/library/svnversion/svnversion.cpp:9:32: fatal error: svnversion_data.h: No such file or directory

**Comment by the31k** [comment]
@pandreym, could you please provide us full build log?

**Comment by pandreym** [comment]
Sorry, it was my problem, lua wasn't locate in default path
