### ISSUE TITLE
Ввод текста из стандартного потока

### ISSUE THREAD

**Issue by logiz** [yandex/tomita-parser#38]
Необходимо ввести текст на обработку Томите через стандартный поток в Windows. При попытке запуска выводятся непрерывно следующие сообщения.
![screen tomita](https://cloud.githubusercontent.com/assets/7427483/12228479/1f2b2bc0-b84d-11e5-8f29-1e8b5261bc20.png)

Как правильно следует подавать поток на обработку Томите?

**Comment by vbocharov** [comment]
tomita-parser.exe config.proto < file.txt

Это работает с минимальным конфигом. Если нужно считать отдельным документом каждую строку входного потока (а не весь входной поток), то нужно сделать так (в конфиге):

Input = { Type = dpl; }

Если ничего не помогает, приложите, пожалуйста, к тикету ваш конфиг и строку запуска.
