### ISSUE TITLE
При создании библиотеки Mystem возникает ошибка

### ISSUE THREAD

**Issue by SerzhNS** [yandex/tomita-parser#43]
I'm sorry for disturbing.
Pls. discard this issue.
The answer has been found on Yandex Mystem page.

См. выдачу:

Scanning dependencies of target library-malloc-api
[  0%] Building CXX object library/malloc/api/CMakeFiles/library-malloc-api.dir/malloc.cpp.o
Linking CXX static library liblibrary-malloc-api.a
[  0%] Built target library-malloc-api
Scanning dependencies of target tools-bison-gnulib
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/abitset.c.o
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/argmatch.c.o
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/asnprintf.c.o
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/basename-lgpl.c.o
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/basename.c.o
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/binary-io.c.o
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/bitrotate.c.o
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/bitset.c.o
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/bitset_stats.c.o
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/bitsetv-print.c.o
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/bitsetv.c.o
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/c-ctype.c.o
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/c-stack.c.o
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/c-strcasecmp.c.o
[  0%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/c-strncasecmp.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/calloc.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/clean-temp.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/cloexec.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/close-stream.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/close.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/closein.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/closeout.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/concat-filename.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/dirname-lgpl.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/dirname.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/dup-safer-flag.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/dup-safer.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/dup2.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/ebitset.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/error.c.o
[  1%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/execute.c.o
[  3%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/exitfail.c.o
[  3%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/fatal-signal.c.o
[  3%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/fclose.c.o
[  3%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/fcntl.c.o
[  3%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/fd-hook.c.o
[  3%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/fd-safer-flag.c.o
[  3%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/fd-safer.c.o
[  3%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/fflush.c.o
[  3%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/filenamecat-lgpl.c.o
[  3%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/filenamecat.c.o
[  3%] Building C object contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/float.c.o
/home/ssn/tomita-parser-1.0/src/contrib/tools/bison/gnulib/src/float.c:27:13: error: variable ‘gl_LDBL_MAX’ has initializer but incomplete type
 const union gl_long_double_union gl_LDBL_MAX =
             ^
/home/ssn/tomita-parser-1.0/src/contrib/tools/bison/gnulib/src/float.c:28:3: error: extra brace group at end of initializer
   { { 0xFFFFFFFF, 0xFFFFFFFF, 32766 } };
   ^
/home/ssn/tomita-parser-1.0/src/contrib/tools/bison/gnulib/src/float.c:28:3: error: (near initialization for ‘gl_LDBL_MAX’)
make[2]: *** [contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/src/float.c.o] Ошибка 1
make[1]: *** [contrib/tools/bison/gnulib/CMakeFiles/tools-bison-gnulib.dir/all] Ошибка 2
make: *** [all] Ошибка 2

Как можно решить проблему?

**Comment by dustalov** [comment]
Чтобы разработчики парсера могли разобраться в причинах проблемы, необходимо уточнить дополнительную информацию. На какой системе, на каком компиляторе, какой версии CMake и какими командами выполняется сборка?
