### ISSUE TITLE
Как декодировать вывод в формате proto?

### ISSUE THREAD

**Issue by alexbat98** [yandex/tomita-parser#45]
Как использовать вывод в формате protobuf? Попытка подключить facttypes.proto приводит к ошибке компиляции при импорте, а при создании своего proto файла с теми же сообщениями и полями выдаются ошибки (`Decoded message is not valid`). Для декодирования используется https://github.com/mafintosh/protocol-buffers

Свой собственный proto файл имеет вид:
```
message Facts {
 message Fact1 {
  required string field1 = 1;
  optional string field2 = 2;
 }
 repeated Fact1 facts = 1;
}
```

Чтение выполняется из stdout:
```
proc.stdout.on('data', function (data) {
    var tmp = message.Facts.decode(data);
    console.log(tmp);
});
```

**Comment by unkmas** [comment]
Привет!

Посмотреть на декодирование можно тут https://github.com/yandex/tomita-parser/tree/master/examples/parsefacts
