### ISSUE TITLE
Возможно ли построение дерева синтаксического разбора?

### ISSUE THREAD

**Issue by mnvx** [yandex/tomita-parser#49]
Возможно ли с помощью Томита-парсера получить дерево синтаксического разбора наподобиe
![](https://hsto.org/getpro/habr/post_images/3a7/db5/091/3a7db50916d9028adcc3161f0a9dbe76.jpg)
(картинка [отсюда](https://habrahabr.ru/company/yandex/blog/205198/))

В конфиге можно задать параметр `PrintTree` для вывода дерева синтаксического разбора. Но для того, чтобы получить это дерево, надо обязательно задавать конкретные правила?

У меня произвольные тексты (сотни тысяч новостных документов), их нужно разбить на предложения и для каждого предложения построить дерево синтаксического разбора. Не представляю как можно описать правила для того, чтобы строились деревья синтаксического разбора для целых предложений.

Для моей задачи подойдет Томита-парсер или надо искать другое решение?

**Comment by victorbocharov** [comment]
Да, томита-парсер - это инструмент для обработки текста правилами.
Для вашей задачи можно попробовать https://github.com/tensorflow/models/blob/master/syntaxnet/universal.md

**Comment by mnvx** [comment]
@victorbocharov Спасибо! До этого пробовал MaltParser, но там для русского языка получилось запустить анализ только на версии 1.5 (при том, что сейчас актуальная версия 1.9).
Попробовал сейчас TensorFlow с моделью SynTagRus. Отлично работает, думаю для моего случая подойдет вполне.
