### ISSUE TITLE
Ограничение на 25 извлеченных фактов

### ISSUE THREAD

**Issue by bloodcarter** [yandex/tomita-parser#61]
Собирал не из исходников, а скачал бинарник для Win64. Получил вот такой ответ:
Too many facts of type "SingularJob" found (47), will be ignored.
The current limit is 25.

Это чем обосновано и как можно обойти без пересборки?

P.S. кстати, судя по исходникам, у вас там должно стоять ограничение 128 фактов.

**Comment by shtrih** [comment]
Для тех, кто пришел сюда из гугла. 
Данный лимит фактов относится к одному предложению. 
(То есть если вы просто накидали рандомного текста в input.txt и видите предупреждение «… The current limit …» — расставьте точки и/или двойные переносы строк).
Значение по умолчанию: https://github.com/yandex/tomita-parser/blob/21c4d7c62648316d05dbd49c6649ec67e5059320/src/FactExtract/Parser/common/textminerconfig.proto#L148
