### ISSUE TITLE
Каким образом реализована многопоточность?

### ISSUE THREAD

**Issue by bloodcarter** [yandex/tomita-parser#63]
Каким образом реализована многопоточность? Что фактически делает параметр NumThreads?

Я не заметил никакой разницы с NumThreads = 1 и NumThreads = 4 на 4х ядерном процессоре, ни в плане скорости, ни в плане загрузки процессоров.

Что мне делать, если мне надо оптимизировать производительность? У меня сейчас 5500 правил в грамматике и уже ощутимо долго думает. Спасибо.

**Comment by victorbocharov** [comment]
Если NumThreads > 1, то разные документы будут разбираться в разных потоках.
Смотреть на реализацию многопоточности лучше отсюда: src/FactExtract/Parser/simpletextminerlib/simpleprocessor.cpp

Ввод блокирующий (https://github.com/yandex/tomita-parser/blob/master/src/FactExtract/Parser/textminerlib/processor.cpp#L234), т.е. если один документ обрабатывается быстро (по сравнению со временем его чтения с диска), то эффект от многопоточности будет невелик.

Про оптимизацию: какие-то части может быть можно перенести из грамматики в словарь?
Трудно ответить, не видя грамматики.

**Comment by bloodcarter** [comment]
Ну если бы вы согласились взглянуть на моя грамматику, то я бы был признателен. Куда ее отправить? Тут нечитаемо будет.

**Comment by vbocharov** [comment]
victor.bocharov@gmail.com
Посмотрю вечером. Прямо сейчас не успею.

**Comment by vbocharov** [comment]
Мне пока ничего не пришло почтой.

**Comment by bloodcarter** [comment]
Я думаю, это уже к issues не относится. Закрываю.
