### ISSUE TITLE
Не работает согласование sp-agr

### ISSUE THREAD

**Issue by bloodcarter** [yandex/tomita-parser#65]
Правило такое:
S -> Verb<sp-agr[1]> interp (F.A) Noun<sp-agr[1]> interp (F.B);

Компилируется, но просто не ловит.

**Comment by vbocharov** [comment]
Я проверил на цепочках: "бежит мальчик", "бежал мальчик" и "бежала мальчик". Первые две сработали, последняя - нет. А на каких не работает у вас?

**Comment by bloodcarter** [comment]
Ну например, "уложить   плитку".

**Comment by vbocharov** [comment]
Это не отношение субъект - предикат, поэтому не срабатывает. "плитку" по отношению к "уложить" - это прямое дополнение. Чаще всего оно в винительном падеже. Можно проверять именно это.

sp-agr проверяет согласование подлежащего (субъекта) и сказуемого (предиката). Подлежащее всегда в именительном падеже. Сказуемое - личная форма глагола, в данном случае (другие варианты sp-agr, похоже, не понимает).
