### ISSUE TITLE
Не работает пример с protobuf для python

### ISSUE THREAD

**Issue by tonal** [yandex/tomita-parser#68]
Воспроизведение:
```
$ cd tomita-parser/examples/parsefacts/Python
$ ./generate.sh
../facts.proto: No such file or directory
```

**Comment by MartSlaaf** [comment]
facts.proto почему-то лежит в соседней директории, которая про C++

**Comment by tonal** [comment]
Это я тоже нашел.
Но думаю, что разработчики должны определится где ему должно лежать и соответственно поправить скрипты компиляции.
