### ISSUE TITLE
Нужен пример компиляции своих фактов в protobuf

### ISSUE THREAD

**Issue by tonal** [yandex/tomita-parser#69]
Пытаюсь скомпилировать файл с фактами в protobuf и получаю ошибку:
```
cd tomita-parser/examples/tutorial4
$ protoc -I . --python_out=. facttypes.proto 
facttypes.proto:4:13: Expected "{".
```
Добавьте, пожалуйста, пример, как корректно компилить файлы с фактами.

**Comment by MartSlaaf** [comment]
Посредством некоторого количества проб и ошибок выяснено следующее:

1) Первым делом надо свой *.proto перекомпилить при помощи утилки gzt-compiler  подробности см. в его хелпе. Насколько я понимаю, перед этим придется заменить импорт base.proto на kernel/gazetteer/base.proto - впрочем, он сам все расскажет ошибкой. Может это не обязательно, я пока не вник.
2) Нагенерить при помощи protoc  питоньи файлы для своих facttypes.proto, уже сконверченных.
3) Нагенерить таким же образом все необходимые импорты из разных частей проекта, а так же нагенерить файл из facts.proto (он лежит в папке examples/parsefacts/C++).
4) В принципе на этом месте можно начинать пользоваться скриптом из примера examples/parsefacts/Python.

Чуть позже я думаю, смогу выложить нагенеренные стандартные питоньи файлы (останется генерить только facttypes), или может даже более адекватный скрипт для сборки.

Не факт, что этот путь оптимален. Но он по крайней мере выглядит рабочим =)

**Comment by vbocharov** [comment]
Цепочка кажется очень сложной, либо я не понимаю проблему. В репозитории от соревнования по извлечению фактов есть пример, где tomita-parser генерирует факты в protobuf, после чего эти факты переводятся в другой формат программой на питоне. Посмотрите, пожалуйста, решает ли это проблему: https://github.com/victorbocharov/factRuEval-2016-sample

**Comment by denis-ivanov** [comment]
@tonal смогли в итоге скомпилировать?

**Comment by denis-ivanov** [comment]
@vbocharov по ссылке те же ошибки возникают.

**Comment by victorbocharov** [comment]
Что говорит protoc --version ?

**Comment by vovagp** [comment]
Внешний (v3, но дефолтно работает в v2) и внутренний (в репе) protoc'и не понимают Date: NFactType.TFact

**Comment by victorbocharov** [comment]
Кажется, я понял. Не нужно компилировать facttypes.proto. Его компилирует сам tomita-parser, т.к. facttypes.proto обычно импортирован из корневого словаря. Судя по всему @MartSlaaf пытается повторить вручную то, что происходит внутри томиты при компиляции. Этого делать не нужно.

protoc нужен в том случае, когда protobuf выбран в качестве выходного формата фактов у tomita-parser, и вы хотите, чтобы ваша программа этот файл с фактами в формате protobuf прочитала. Примеры на этот случай лежат в папке examples/parsefacts . Везде, где нужен protoc, рядом лежит соответствующий bash - скрипт (в примере с C++ - Makefile). Если ничего похожего рядом нет, значит подразумевалось, что protoc не нужен.

**Comment by denis-ivanov** [comment]
@victorvocharov именно в формате protobuf я и собираюсь считывать данные. Но protoc упадет из-за причин пеинчисленных выше @vovagp.

**Comment by denis-ivanov** [comment]
@victorbocharov

**Comment by victorbocharov** [comment]
@denis-ivanov вам нужно скомпилировать при помощи protoc только файл facts.proto ( examples/parsefacts/facts.proto ). При этом в него не нужно вносить изменений, т.к. это не файл-пример, а готовое описание встроенных типов. Компилируйте его как есть. 

Файл facttypes.proto (или любой другой файл с описанием фактов, который вы составили сами) не нужно компилировать при помощи protoc. Это задача tomita-parser.

**Comment by denis-ivanov** [comment]
@victorbocharov если я скомпилирую только встроенные типы, то как мне читать собстенные факты?

**Comment by denis-ivanov** [comment]
Кажется понял

**Comment by victorbocharov** [comment]
@denis-ivanov Все факты (в том числе и те, которые вы сами определили) представляют собой списки полей. У поля есть имя и значение. Документ состоит из списка типов фактов, внутри типа перечислены факты этого типа. Вот пример из parsefacts/Python:

```
    for fg in doc.FactGroup:
      print "fact type =", fg.Type

      for f in fg.Fact:
        print "index =", f.Index

        for field in f.Field:
          print field.Name, "=", field.Value
```

Типов полей не много, и все они описаны в facts.proto. Создать новый тип поля штатными средствами нельзя.

**Comment by victorbocharov** [comment]
Прошу участников обсуждения отписаться явно, что всё получилось и тикет можно закрывать ;)

**Comment by tonal** [comment]
Собственно непонятки происходят из за попыток скомпилить свои *.proto файлы и ожидания получить скрипты на python-е, которые будут разбирать выдачу в формате protobuf. По аналогии с С++.
Но Python - язык динамический, поэтому никаких дополнительных скриптов кроме стандартного, получаемого из facts.proto не требуется.
Думаю можно закрывать. :)
