### ISSUE TITLE
Не получается скомпилить парсер

### ISSUE THREAD

**Issue by andymitrich** [yandex/tomita-parser#74]
Система:
 - ubuntu 14.04 LTS x64
 - gcc version 4.8.4
 - lua 5.2.3
 - cmake version 2.8.12.2

Компилю:
`andy@pc:~/tomita/tomita-parser/build$ cmake ../src/ -DCMAKE_BUILD_TYPE=Release`

Получаю такой вывод:
```-- The CXX compiler identification is unknown
CMake Error: your CXX compiler: "CMAKE_CXX_COMPILER-NOTFOUND" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
CMake Error at cmake/include/tools.cmake:328 (MESSAGE):
  tools.cmake: Can't get gcc native include path
Call Stack (most recent call first):
  cmake/include/global.cmake:167 (INCLUDE)
  CMakeLists.txt:27 (INCLUDE)


CMake Error at cmake/include/tools.cmake:417 (MESSAGE):
  tools.cmake: /usr/lib/gcc///libsupc++.a doesn't exist (with positive
  USE_STATIC_CPP_RUNTIME)
Call Stack (most recent call first):
  cmake/include/global.cmake:167 (INCLUDE)
  CMakeLists.txt:27 (INCLUDE)


-- Cached: CMAKE_BUILD_TYPE[Release]
CMake Error: your CXX compiler: "CMAKE_CXX_COMPILER-NOTFOUND" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
CMake Error: your CXX compiler: "CMAKE_CXX_COMPILER-NOTFOUND" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
CMake Error at cmake/include/dtmk.cmake:205 (IF):
  if given arguments:

    "GREATER" "30000"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/include/buildrules.cmake:1945 (EXEC_DTMK)
  cmake/include/buildrules.cmake:1257 (ADD_LIBRARY_EX)
  contrib/tools/bison/gnulib/CMakeLists.txt:222 (END)
```

Есть еще пару файлов CMakeError.log (https://drive.google.com/open?id=0B40GtZqm3deqeUNhTE96V1dDUGs) и CMakeOutput.log (https://drive.google.com/open?id=0B40GtZqm3deqcTZjTXpjRU1BYkU)

**Comment by vbocharov** [comment]
Не удалось воспроизвести на 14.04.1 и 14.04.5 . Попробуйте поставить пакет build-essential .

**Comment by andreqwert** [comment]
Тоже не удаётся скомпилить, macOS 10.10.
cmake, gcc, lua - все версии последние.
Тоже компилю: cmake ../src/ -DCMAKE_BUILD_TYPE=Release

Ошибка: 
``` CMake Error at cmake/include/tools.cmake:417 (MESSAGE):
  tools.cmake: libsupc++.a/libsupc++.a doesn't exist (with positive
  USE_STATIC_CPP_RUNTIME) 
```

**Comment by ice1x** [comment]
> Тоже не удаётся скомпилить, macOS 10.10.
> cmake, gcc, lua - все версии последние.
> Тоже компилю: cmake ../src/ -DCMAKE_BUILD_TYPE=Release
> 
> Ошибка:
> 
> ```cmake
>   tools.cmake: libsupc++.a/libsupc++.a doesn't exist (with positive
>   USE_STATIC_CPP_RUNTIME) 
> ```

Та же проблема на 10.11.6
