### ISSUE TITLE
Инструкция по сборке примеров

### ISSUE THREAD

**Issue by denis-ivanov** [yandex/tomita-parser#76]
Добрый день!
Хотелось бы иметь инструкцию по сборке примеров. После сборки tomita-parser примеры просто так собрать не получается, потому что при запуске make в папке `examples/parsefacts/C++` сначала не находит утилиты, после добавления их в `PATH` ругается что не может найти заголовочные файлы protobuf подключенные так: https://github.com/yandex/tomita-parser/blob/master/examples/parsefacts/C%2B%2B/main.cpp#L7

Хотя в сгенерированном коде protobuf подключается из директории `src/contrib/libs/protobuf/`.

**Comment by vbocharov** [comment]
на какой OS make было недостаточно для этого примера?

**Comment by denis-ivanov** [comment]
Ubuntu 16.04.2.
make install после установки делать было нужно?

**Comment by vbocharov** [comment]
нет, make install не нужно.

Этому примеру нужен protobuf из репозитория Ubuntu. При этом все пути проставятся автоматически. Он устанавливается так:

`sudo apt-get install protobuf-compiler libprotobuf-dev`

**Comment by denis-ivanov** [comment]
@vbocharov спасибо. После установки указанных пакетов пример собрался.

Хотелось бы знать, есть ли какое-то руководство, как использовать парсер именно для извлечения фактов из кода. Вся документация на сайте - https://tech.yandex.ru/tomita/ описывает только извлечение фактов с помощью консольной утилиты tomita-parser.exe.

**Comment by denis-ivanov** [comment]
@vbocharov у меня представление такое, что можно написать грамматики, в коде их подгрузить и парсить текст, но реальных примеров я найти не могу.
