### ISSUE TITLE
Статус поддержки других языков

### ISSUE THREAD

**Issue by aeryaguzov** [yandex/tomita-parser#77]
Привет.

Отлично работает на русском языке, очень хочется попробовать другие. 

На хабре писали (https://habrahabr.ru/company/yandex/blog/219311/#comment_7495071), что будет такая возможность, когда выложите проект. 

Расскажите пожалуйста про поддержку других языков

**Comment by bloodcarter** [comment]
+

**Comment by rin-nas** [comment]
Присоединяюсь
