### ISSUE TITLE
Некорректная интерпретация "количественного числительного"

### ISSUE THREAD

**Issue by Userator** [yandex/tomita-parser#85]
> config.proto.test
```
encoding "utf8";

TTextMinerConfig {
	Dictionary = "./dic.gzt"

	Articles = [
		{Name = "AmountArticle"}
	]

	Facts = [
		{Name = "FAmount"}
	]

	PrettyOutput = "./prety.html";

	PrintTree = "./tree.txt";
	PrintRules = "./rules.txt";

	Input = {
		File = "./input.txt";
		Type = dpl;
	}

	Output = {
		Mode = overwrite;
		Format = text;
	}
}
```
> dic.gzt
```
encoding "utf8";

import "base.proto";
import "articles_base.proto";

import "facttypes.proto"; // описание фактов
import "kwtypes.proto"; // описание типов словарей

TAuxDicArticle "AmountArticle" {
	key = {"tomita:grammar/amount.cxx" type=CUSTOM}
}
```
> amount.cxx
```
#encoding "utf8"
#GRAMMAR_ROOT Root

Root -> Word<gram='NUM'> interp(FAmount.Num);
Root -> Word<gram='ANUM'> interp(FAmount.Anum);
```
> facttypes.proto
```
import "base.proto";
import "facttypes_base.proto";

message FAmount: NFactType.TFact {
	optional string Num = 1;
	optional string Anum = 2;
}
```
> kwtypes.proto
```
import "base.proto";
import "articles_base.proto";
import "kwtypes_base.proto";
```
> input.txt
```
один час назад
два часа назад
```
> Результат интерпретации
```
один час назад 
	FAmount
	{
		Anum = один
	}
два часа назад 
	FAmount
	{
		Num = два
	}
```
Слово "один" интерпретировалось как "порядковое числительное" соответствующее граммеме "ANUM", хотя, согласно правилам русского языка, является "количественным числительным" и должно соответствовать граммеме "NUM"

**Comment by vbocharov** [comment]
Томита использует mystem в качестве морфологии. Для "один" там решено использовать граммему ANUM.

Слово "один" ведёт себя не только как количественное числительное. Вот здесь об этом написано подробнее:
- http://rusgram.narod.ru/1366-1383.html
- http://rusgram.ru/Числительное#3

**Comment by Userator** [comment]
Виктор спасибо.

Сейчас данную особенность обхожу с помощью следующих правил:

`Num -> Word<kwtype=num, gram='NUM'>;`
`Num -> Word<kwtype=num, wfl='^.*один$'>;`
`Anum -> Word<kwtype=num, gram='ANUM', wfl=~'^.*один$'>;`
