### ISSUE TITLE
Tomita Parser error

### ISSUE THREAD

**Issue by yellowsniff** [yandex/tomita-parser#88]
Код файла config.proto:

encoding "utf8";

TTextMinerConfig {
	Dictionary = "dic.gzt";
  
	Input = { 
		File = "test.txt";
	}

	Output = {
		File = "output.txt";
		Format = text;
	}
  
	Articles = [
		{ Name = "адрес" } 
	]
	
	Facts = [
		{ Name = "Address" }
	]
}

После запуска выдает ошибку: [09:04:18 16:40:11] - Bad parameters.
util\charset\wide.h:711: failed to decode UTF-8 string at pos 0 in string "\xE0\xE4\xF0\xE5\xF1"(Processing files.)
Yandex Tomita-parser (build date Jan 24 2013)
Usage: tomitaparser configuration_file.proto

С кодировкой обрабатываемого файла все в порядке.

**Comment by grandsbor** [comment]
Приложите, пожалуйста, файл test.txt, если проблема ещё актуальна.
